import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Monitor from '../../public/images/monitor.gif'
import styleBorder from '../styles/Border.module.css'
import circle2 from "../../public/images/circle.png";
import ParticleBg from "../components/ParticleBg";
import Title from '../components/title'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://brathkennet.github.io/career-portfolio/icons/favicon.ico"
        />
      </Head>

      <header className="flex items-center justify-around h-screen bg-no-repeat bg-center bg-cover bg-[url('../../public/images/bg-section1.jpeg')] z-50  ">
        <div
          className="bg-[black]/25 z-10 backdrop-blur-md border-4 border-[#C00B62] rounded-tr-[52px] rounded-bl-[52px] md:p-16 p-7 m-12"
          data-aos="zoom-in"
        >
          <p
            className={`text-white text-center md:text-5xl text-3xl lg:mb-8 mb-6 ${styles.section_title} `}
          >
            Desarrollo de Aplicaciones Web
          </p>
          <p
            className={`text-white text-center lg:text-2xl text-sm ${styles.section_subtitle}`}
          >
            Portafolio Electrónico
          </p>
        </div>
      </header>

      <section className="h-fit bg-[#13000E] z-20 pt-28 pb-10 sm:px-28 px-8 max-w-screen">
        <Title text={"Bienvenida e Introducción"} right={true} />
        <div className="grid md:grid-cols-2 grid-cols-1 lg:px-20 sm:px-0 md:py-12 py-5 place-items-center">
          <div data-aos="zoom-in-right">
            <Image src={Monitor} height={400} width={400} alt="monitor" />
          </div>
          <div
            className="w-fit h-fit border-x border-white md:mt-0 mt-5 sm:px-10 px-5 sm:py-10 py-5 sm:rounded-[40px] rounded-[20px]"
            data-aos="zoom-in-left"
          >
            <p
              className={`text-white max-w-[400px] text-justify m-auto lg:text-[19px] text-base ${styles.text_font}
              `}
            >
              ¡Bienvenido al portafolio electrónico de Desarrollo de
              Aplicaciones Web! <br />
              <br /> Mi nombre es Brath, y estoy emocionado de compartir mi
              trabajo y mi trayectoria durante este curso. <br />
              <br />
              En este portafolio encontrarás los temas realizados por cada
              semana. Cada uno de ellos representa un reto para mí y una
              oportunidad para aprender y crecer en mi carrera.
            </p>
          </div>
        </div>
      </section>
      <hr />
      <section className="h-fit bg-[#13000E] z-20 pt-28 pb-10 sm:px-28 px-8 max-w-screen ">
        <Title text={"Contenido"} right={false} />

        <div className={styles.main}>
          <div className={styles.container}>
            <ul>
              <li>
                <div className={styles.super}>
                  <div className={styles.div1}> Semana 1</div>
                  <div className={styles.div2}>
                    <h3 className={styles.title}>Front End Developer</h3>
                    <p>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Dolorem eaque quidem esse? Incidunt, odit beatae?
                    </p>
                    <a >Read More {">"}</a>
                  </div>
                </div>
                <span className={styles.circle}></span>
              </li>
              <li>
                <h3 className={styles.title}>Back End Developer</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Dolorem eaque quidem esse? Incidunt, odit beatae?
                </p>
                <a >Read More {">"}</a>
                <span className={styles.circle}></span>
              </li>
              <li>
                <h3 className={styles.title}>Full Stack Developer</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Dolorem eaque quidem esse? Incidunt, odit beatae?
                </p>
                <a >Read More {">"}</a>
                <span className={styles.circle}></span>
              </li>
              <li>
                <h3 className={styles.title}>App Developer</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Dolorem eaque quidem esse? Incidunt, odit beatae?
                </p>
                <a >Read More {">"}</a>
                <span className={styles.circle}></span>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </>
  );
}
