import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex justify-around items-stretch h-screen bg-no-repeat bg-center bg-cover bg-[url('../public/bg-section1.jpeg')]">
        <div className="self-center bg-[black]/25 border-4 border-[#C00B62] rounded-tr-[52px] rounded-bl-[52px] backdrop-blur-md lg:p-16 p-10 m-12">
          <p
            className={`text-white text-center md:text-5xl text-2xl mb-8 ${styles.section_title}`}
          >
            Desarrollo de Aplicaciones Web
          </p>
          <p
            className={`text-white text-center md:text-2xl text-sm ${styles.section_subtitle}`}
          >
            Portafolio Electrónico
          </p>
        </div>
      </section>
    </>
  );
}
