import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/layouts/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://brathkennet.github.io/career-portfolio/favicon.ico"
        />
      </Head>

      <section className="flex items-center justify-around h-screen bg-no-repeat bg-center bg-cover bg-[url('../public/images/bg-section1.jpeg')]">
        <div className="bg-[black]/25 z-10 backdrop-blur-md border-4 border-[#C00B62] rounded-tr-[52px] rounded-bl-[52px] md:p-16 p-7 m-12 ">
          <p
            className={`text-white text-center md:text-5xl text-3xl lg:mb-8 mb-6 ${styles.section_title}`}
          >
            Desarrollo de Aplicaciones Web
          </p>
          <p
            className={`text-white text-center lg:text-2xl text-sm ${styles.section_subtitle}`}
          >
            Portafolio Electrónico
          </p>
        </div>
      </section>
      <section className="z-30 flex items-center justify-around h-screen bg-no-repeat bg-center bg-cover bg-[url('../public/images/bg-section1.jpeg')]">
        <div className=" bg-[black]/25 z-10 backdrop-blur-md border-4 border-[#C00B62] rounded-tr-[52px] rounded-bl-[52px]   md:p-16 p-7 m-12">
          {/* md:backdrop-blur-md */}
          <p
            className={`text-white text-center md:text-5xl text-3xl lg:mb-8 mb-6 ${styles.section_title}`}
          >
            Desarrollo de Aplicaciones Web
          </p>
          <p
            className={`text-white text-center lg:text-2xl text-sm ${styles.section_subtitle}`}
          >
            Portafolio Electrónico
          </p>
        </div>
      </section>
    </>
  );
}
